### ISSUE TITLE
how to send uInt64 type field?

### ISSUE THREAD

**Issue by qumeta** [NetEase/pomelo-unitychat-socket#1]
Dictionary<string, int> dic = new Dictionary<string, int>();
dic.Add("uInt32", 0);
dic.Add("sInt32", 0);
dic.Add("int32", 0);
dic.Add("double", 1);
dic.Add("string", 2);
dic.Add("float", 5);
dic.Add("message", 2);

Int64 uInt64 missing?

**Comment by qumeta** [comment]
oh. msgDecoder.js does't decoder in64

**Comment by demon0925** [comment]
Because we use node.js as server, and js doesn't support int64. For
compatibility, all the protobuf clients
don't support int64. To use int64,you can transfer data without protobuf or
transfer  the int64 to string.
ÔÚ 2013-4-25 ÏÂÎç2:26£¬"lilinghui" notifications@github.comÐ´µÀ£º

**Comment by demon0925** [comment]
yes, js dones't support int64
ÔÚ 2013-4-25 ÏÂÎç2:29£¬"lilinghui" notifications@github.comÐ´µÀ£º

**Comment by qumeta** [comment]
ths

**Comment by francislyj** [comment]
ths
